site_name: WebSight CMS
site_description: 'Explore materials, tutorials and documentation to discover how to use WebSight effectively. Discover enterprise grade, web-scale content management system.'
site_author: 'Dynamic Solutions'
site_url: 'https://docs.websight.io'
copyright: Copyright &copy; Dynamic Solutions

theme:
  name: material
  custom_dir: 'theme'
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    # - navigation.tracking
    # - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: white
      accent: blue

repo_name: websight-io/starter
repo_url: https://github.com/websight-io/starter
edit_uri: ../docs/edit/main/docs

extra_css:
  - assets/stylesheets/websight.css

extra_javascript:
  - assets/javascripts/cookieconsent.js
  - assets/javascripts/cookieconsent_init.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Custom directories to watch for changes while running `mkdocs serve`
watch:
  - theme

extra:
  analytics:
    provider: gtm
    property: GTM-M2B8LK4
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/websight-io
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/websight_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/websight-io/
    - icon: fontawesome/brands/docker
      link: https://gallery.ecr.aws/ds

plugins:
  - awesome-pages
  - search
  - include-markdown
  - redirects:
      redirect_maps:
          'simulator': 'https://architectures-load-simulator-pk7p5jx36a-lm.a.run.app'

          # Redirects for empty nodes

          'index.md': 'cms/intro/index.md'
          'cms/index.md': 'cms/intro/index.md'
          'cms/developers/index.md': 'cms/developers/quick-start/index.md'
          'cms/authors/index.md': 'cms/authors/component-libs/howlite/index.md'
          'cms/authors/component-libs/index.md': 'cms/authors/component-libs/howlite/index.md'
          'cms/deployment/index.md': 'cms/deployment/kubernetes/index.md'
          'cms/release-notes/index.md': 'cms/release-notes/websight-cms/index.md'

          # legacy URL / moved pages
          'cms/release-notes/websight-cms/index.md': 'cms/release-notes/index.md'
          'cms/architecture/cms-modules-layers/index.md': 'cms/architecture/layers-and-modules/index.md'
