site_name: WebSight DXP
site_description: 'Explore materials, tutorials and documentation to discover how to use WebSight effectively. Discover enterprise grade, web-scale content management system.'
site_author: 'Dynamic Solutions'
site_url: 'https://websight.io'
copyright: Copyright &copy; Dynamic Solutions

theme:
  name: material
  custom_dir: 'theme'
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: white
      accent: blue

repo_name: websight-io/starter
repo_url: https://github.com/websight-io/starter
edit_uri: ../docs/edit/main/docs

extra_css:
  - assets/stylesheets/websight.css

extra_javascript:
  - assets/javascripts/cookieconsent.js
  - assets/javascripts/cookieconsent_init.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Custom directories to watch for changes while running `mkdocs serve`
watch:
  - theme

extra:
  analytics:
    provider: gtm
    property: GTM-M2B8LK4
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/websight-io
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/websight_io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/websight-io/
    - icon: fontawesome/brands/docker
      link: https://gallery.ecr.aws/ds

plugins:
  - awesome-pages
  - search
  - include-markdown
  - blogging:
      locale: en
      dirs:
        - blog/2022
        - blog/2023
      template: theme/ws-blog.html
  - redirects:
      redirect_maps:
          'simulator': 'https://architectures-load-simulator-pk7p5jx36a-lm.a.run.app'
          'docs/index.md': 'docs/quick-start/index.md'
          'docs/authors/index.md': 'docs/authors/component-libs/howlite/index.md'
          'docs/authors/component-libs/index.md': 'docs/authors/component-libs/howlite/index.md'
          'docs/release-notes/index.md': 'docs/release-notes/websight-cms-ce/index.md'

          'docs/developers/deployment/index.md': 'docs/developers/deployment/aws-ecs/index.md'

          'docs/release-notes/websight-cms-ce/index.md' : 'docs/release-notes/websight-cms/index.md'

          'getting-started/quick-start/index.md': 'docs/quick-start/index.md'
          'guides/authoring/howlite/index.md': 'docs/authors/component-libs/howlite/index.md'
          'guides/authoring/howlite/accordion/index.md': 'docs/authors/component-libs/howlite/accordion/index.md'
          'guides/authoring/howlite/cards-list/index.md': 'docs/authors/component-libs/howlite/cards-list/index.md'
          'guides/authoring/howlite/container/index.md': 'docs/authors/component-libs/howlite/container/index.md'
          'guides/authoring/howlite/cta/index.md': 'docs/authors/component-libs/howlite/cta/index.md'
          'guides/authoring/howlite/grid/index.md': 'docs/authors/component-libs/howlite/grid/index.md'
          'guides/authoring/howlite/image/index.md': 'docs/authors/component-libs/howlite/image/index.md'
          'guides/authoring/howlite/layouts/index.md': 'docs/authors/component-libs/howlite/layouts/index.md'
          'guides/authoring/howlite/logo-cloud/index.md': 'docs/authors/component-libs/howlite/logo-cloud/index.md'
          'guides/authoring/howlite/page-section/index.md': 'docs/authors/component-libs/howlite/page-section/index.md'
          'guides/authoring/howlite/quote/index.md': 'docs/authors/component-libs/howlite/quote/index.md'
          'guides/authoring/howlite/rte/index.md': 'docs/authors/component-libs/howlite/rte/index.md'
          'guides/authoring/howlite/title/index.md': 'docs/authors/component-libs/howlite/title/index.md'

          'docs/developers/dialogs/richtext-editor/richtext-editor-configuration/index.md' : 'docs/developers/development/dialogs/richtext-editor/configuration/index.md'
          'docs/developers/dialogs/richtext-editor/richtext-editor-plugin-components/index.md' : 'docs/developers/development/dialogs/richtext-editor/plugin-components/index.md'
          'docs/developers/dialogs/richtext-editor/richtext-editor-ui-components/index.md' : 'docs/developers/development/dialogs/richtext-editor/ui-components/index.md'
          'docs/developers/dialogs/richtext-editor/richtext-editor-ui-components/button/index.md' : 'docs/developers/development/dialogs/richtext-editor/ui-components/button/index.md'
          'docs/developers/dialogs/richtext-editor/richtext-editor-ui-components/button-dropdown/index.md' : 'docs/developers/development/dialogs/richtext-editor/ui-components/button-dropdown/index.md'
          'docs/developers/dialogs/richtext-editor/richtext-editor-ui-components/dropdown/index.md' : 'docs/developers/development/dialogs/richtext-editor/ui-components/dropdown/index.md'
          'docs/developers/dialogs/richtext-editor/richtext-editor-ui-components/link/index.md' : 'docs/developers/development/dialogs/richtext-editor/ui-components/link/index.md'

          'docs/developers/create-and-develop-project/index.md' : 'docs/developers/setup/index.md'
          'docs/developers/components/index.md': 'docs/developers/development/components/index.md'
          'docs/developers/components/definition/index.md': 'docs/developers/components/index.md'
          
          'docs/developers/dialogs/index.md': 'docs/developers/development/dialogs/index.md'
          'docs/developers/dialogs/assetreference/index.md': 'docs/developers/development/dialogs/assetreference/index.md'
          'docs/developers/dialogs/checkbox/index.md': 'docs/developers/development/dialogs/checkbox/index.md'
          'docs/developers/dialogs/container/index.md': 'docs/developers/development/dialogs/container/index.md'
          'docs/developers/dialogs/date-picker/index.md': 'docs/developers/development/dialogs/date-picker/index.md'
          'docs/developers/dialogs/include/index.md': 'docs/developers/development/dialogs/include/index.md'
          'docs/developers/dialogs/multifield/index.md': 'docs/developers/development/dialogs/multifield/index.md'
          'docs/developers/dialogs/number-field/index.md': 'docs/developers/development/dialogs/number-field/index.md'
          'docs/developers/dialogs/pathpicker/index.md': 'docs/developers/development/dialogs/pathpicker/index.md'
          'docs/developers/dialogs/radio/index.md': 'docs/developers/development/dialogs/radio/index.md'
          'docs/developers/dialogs/richtext-editor/index.md': 'docs/developers/development/dialogs/richtext-editor/index.md'
          'docs/developers/dialogs/richtext-editor/configuration/index.md': 'docs/developers/development/dialogs/richtext-editor/configuration/index.md'
          'docs/developers/dialogs/richtext-editor/plugin-components/index.md': 'docs/developers/development/dialogs/richtext-editor/plugin-components/index.md'
          'docs/developers/dialogs/richtext-editor/ui-components/index.md': 'docs/developers/development/dialogs/richtext-editor/ui-components/index.md'
          'docs/developers/dialogs/richtext-editor/ui-components/button-dropdown/index.md': 'docs/developers/development/dialogs/richtext-editor/ui-components/button-dropdown/index.md'
          'docs/developers/dialogs/richtext-editor/ui-components/button/index.md': 'docs/developers/development/dialogs/richtext-editor/ui-components/button/index.md'
          'docs/developers/dialogs/richtext-editor/ui-components/dropdown/index.md': 'docs/developers/development/dialogs/richtext-editor/ui-components/dropdown/index.md'
          'docs/developers/dialogs/richtext-editor/ui-components/link/index.md': 'docs/developers/development/dialogs/richtext-editor/ui-components/link/index.md'
          'docs/developers/dialogs/select/index.md': 'docs/developers/development/dialogs/select/index.md'
          'docs/developers/dialogs/tabs/index.md': 'docs/developers/development/dialogs/tabs/index.md'
          'docs/developers/dialogs/tabs/tab/index.md': 'docs/developers/development/dialogs/tabs/tab/index.md'
          'docs/developers/dialogs/text-area/index.md': 'docs/developers/development/dialogs/text-area/index.md'
          'docs/developers/dialogs/textfield/index.md': 'docs/developers/development/dialogs/textfield/index.md'
          'docs/developers/dialogs/toggle/index.md': 'docs/developers/development/dialogs/toggle/index.md'

          'docs/developers/architecture/index.md': 'docs/architecture/index.md'
          'docs/developers/architecture/cms-modules-layers/index.md': 'docs/architecture/cms-modules-layers/index.md'
          'docs/developers/architecture/aws-ecs/index.md': 'docs/architecture/aws-ecs/index.md'
          'docs/developers/architecture/kubernetes/index.md': 'docs/architecture/kubernetes/index.md'

          'docs/developers/deployment/aws-ecs/index.md': 'docs/deployment/aws-ecs/index.md'
          'docs/developers/deployment/kubernetes/index.md': 'docs/deployment/kubernetes/index.md'
          'docs/developers/deployment/linux/index.md': 'docs/deployment/linux/index.md'

          'docs/developers/development/index.md': 'docs/developers/app-development/index.md'
          'docs/developers/development/components/index.md': 'docs/developers/components/index.md'
          'docs/developers/development/components/definition/index.md': 'docs/developers/components/index.md'
          'docs/developers/development/dialogs/index.md': 'docs/developers/dialogs/index.md'
          'docs/developers/development/page-editor/index.md': 'docs/developers/page-editor/index.md'
          'docs/developers/development/page-editor/extending-editor/index.md': 'docs/developers/page-editor/extending-editor/index.md'
          'docs/developers/development/page-editor/side-panel/index.md': 'docs/developers/page-editor/side-panel/index.md'
          'docs/developers/development/wcm-mode/index.md': 'docs/developers/wcm-mode/index.md'

          
